title = "Bubble"
baseURL = "https://blog.hexsix.me/"
theme = "bilberry-hugo-theme/v4"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "zh"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "G-JTDBBWRQP1"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = false

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []
  baseColor = "#F5DAE3"
  specialColor = "#C8839C"
  highlightColor = "#B5C9D9"

  # Description and meta data for the search engines
  author = "hexsix"
  description = "Bubble - 小六家的藏宝图"
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 6

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "TDKNB8DM4V"
  algolia_apiKey    = "932309ed26f5a9d9b5a22c082a4e5a4c"
  algolia_indexName = "blog.hexsix.me"
    # Set this option to false if you want to search within all articles in all languages at once
    algolia_currentLanguageOnly = false

  # Enable / Disable Giscus comments
  giscus             = true
  giscusJsUrl        = "https://giscus.app/client.js"
  giscusRepository   = "hexsix/blog.hexsix.me"
  giscusRepositoryId = "R_kgDOGh4vHw"
  giscusMapping      = "pathname"
  giscusCategory     = "Blog Comments"
  giscusCategoryId   = "DIC_kwDOGh4vH84CAcFP"
  giscusTheme        = "light"
  giscusReactions    = "1"
  giscusEmitMetadata = "0"
  giscusLanguage     = "zh-CN"
  giscusCrossOrigin  = "anonymous"

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "小六家的藏宝图"

    # if you want to use gravatar for the header image
    gravatarEMail = "hexsix@qq.com"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = ""

    # define the icon you want to use for the overlay for the customImage or gravatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/article/installing-bilberry-theme/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatic localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 6

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 6

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = false

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://twitter.com/hexsixology", icon = "fab fa-twitter", rel = "me" },
      { link = "https://github.com/hexsix", icon = "fab fa-github" },
    ]

    # show an archive link in the footer
    showArchive = false

    # archive grouping: "2006" by year, "2006-01" by month
    archiveDateGrouping = "2006-01"

    # credits line configuration
    copyrightBy = "by hexsix"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://github.com/hexsix"
    creditsText = "Bubble"
    creditsUrl = "https://github.com/hexsix/blog.hexsix.me"


# customize your available languages for your multi-lingual site
# or delete the [Languages] blog to use the theme with only one supported language
# [Languages]
#   [Languages.en]
#     weight = 1
#   [Languages.de]
#     weight = 2
#     title = "Mein cooler neuer Blog"
#     subtitle = "Hallo Welt! Dies ist der epischste Untertitel aller Zeiten."

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # change to 'true' if you need to render raw HTML within your markdown content
      unsafe = false
    [markup.highlight]
      anchorLineNos = false
      codeFences = true
      guessSyntax = false
      hl_Lines = ''
      hl_inline = false
      lineAnchors = ''
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = true
      noHl = false
      style = 'monokai'
      tabWidth = 4
    [markup.tableOfContents]
      endLevel = 5
      ordered = false
      startLevel = 2

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
